#!/usr/bin/env python3
import requests
try:
    r = requests.get('https://api.coinbase.com/v2/prices/BTC-USD/spot')
    ticker = r.json()

    price = ticker['data']['amount']
    print('$%.0f' % float(price))
except:
    print('ERROR')
